defaults: &defaults
  steps:
    # common php steps
    - run: echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - run: echo "date.timezone = UTC" >> $(php --ini |grep Scan |awk '{print $NF}')/timezone.ini
    - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

    # install apcu
    - run: |
        docker-php-source extract \
        && apk add --no-cache --virtual .phpize-deps-configure $PHPIZE_DEPS \
        && printf "\n" | pecl install apcu \
        && docker-php-ext-enable apcu \
        && apk del .phpize-deps-configure \
        && docker-php-source delete

    # checkout
    - checkout

    # post-checkout steps

    # run tests
    - run: composer install -n --prefer-dist
    - run: php vendor/phpunit/phpunit/phpunit -c phpunit.xml --log-junit /tmp/test-results/phpunit/junit.xml
    - store_test_results:
        path: /tmp/test-results

version: 2
jobs:
  build-php71:
    <<: *defaults
    docker:
      - image: php:7.1-alpine
  build-php72:
    <<: *defaults
    docker:
      - image: php:7.2-alpine
  build-php73:
    <<: *defaults
    docker:
      - image: php:7.3-alpine
  build-php74:
    <<: *defaults
    docker:
      - image: php:7.4-alpine

workflows:
  version: 2
  build:
    jobs:
      - build-php71
      - build-php72
      - build-php73
      - build-php74
